# Generated by Django 4.2.6 on 2024-02-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=70)),
                ('mdesc', models.CharField(max_length=500)),
                ('mgenre', models.CharField(max_length=50)),
                ('mimg', models.ImageField(upload_to='movie_images/')),
            ],
        ),
    ]
