# Generated by Django 4.2.7 on 2024-02-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='movies1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mdesc', models.CharField(max_length=500)),
                ('myear', models.IntegerField()),
            ],
        ),
    ]
